export const ADD_CONTACT = "ADD_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const CHANGE_TRANSITION = "CHANGE_TRANSITION";
export const CHANGE_TITLE = "CHANGE_TITLE";
export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";
export const TOGGLE_PIN_CONVERSATION = "TOGGLE_PIN_CONVERSATION";
